### PR TITLE
Home page updates phase 2

### PR DESCRIPTION
**Pull request by SaVanceX**
🍏  Ready Go! Sherri has signed off on the updates. 

# Reason for Change 

1. thumbnail should be closer to the date at screen from 1025px to 1365 px range.

2. Quote should be left aligned from mobile, all the way up to 1025px

3. The space above and below the quote should be even. 

## Description of Change

1. Added breakpoint range from 1025px to 1365px to bring the event thumbnail and date closer. 

2. added css to make sure the quote is left aligned from mobile to 1025px

3.  So it looks like I am able have the event above the quote brush up against the top border of the quote. Also in the case if there is an event with a few words the image sets on top of that quote border as well. 

Screenshot 2024-05-13 at 2 41 52 PM
Screenshot 2024-05-13 at 2 42 02 PM

 I believe we discussed also changing the height of that grid cell that holds the event. So that grid cell is also in the same row as the cluster header grid cell. Changing the height is also dependent on the cluster header grid cell height as well. I was playing around with editing the height of the grid cell. Thoughts? This is how it looks at 600px height. 
Screenshot 2024-05-13 at 2 51 25 PM
Screenshot 2024-05-13 at 2 51 44 PM

### CODE REVIEW

**Comment by SaVanceX** [comment]
@YaGirlSherriJ Here are those updates.  https://deploy-preview-351--phot-production.netlify.app/ Let me know if you have any questions!

**Comment by YaGirlSherriJ** [comment]
Thanks @SaVanceX, please see below for feedback. 

> thumbnail should be closer to the date at screen from 1025px to 1365 px range.

- Please move the thumbnail 6px closer to the date
- The Resources block needs the same spacing applied. It's currently still too big.


> Quote should be left aligned from mobile, all the way up to 1025px

- Looks good, thank you!


> The space above and below the quote should be even... So it looks like I am able have the event above the quote brush up against the top border of the quote. Also in the case if there is an event with a few words the image sets on top of that quote border as well.
- The space above the right photo should always be 160px on desktop. It's currently different on a few of them. 

> I believe we discussed also changing the height of that grid cell that holds the event. So that grid cell is also in the same row as the cluster header grid cell. Changing the height is also dependent on the cluster header grid cell height as well. I was playing around with editing the height of the grid cell. Thoughts? This is how it looks at 600px height.
- Can we try the grid height of the first row at 485px?

**Comment by SaVanceX** [comment]
@YaGirlSherriJ are you saying a height of 485px for this row? 
Screenshot 2024-05-14 at 12 53 27 PM

**Comment by YaGirlSherriJ** [comment]
@SaVanceX yes.

**Comment by SaVanceX** [comment]
@YaGirlSherriJ those updates should be available to view now. https://deploy-preview-351--phot-production.netlify.app/

**Comment by YaGirlSherriJ** [comment]
Thanks @SaVanceX - a few things:

1. On desktop sizes above 1365px, this space should be 6px smaller. 

image

3. This space should be 20px smaller to match the above spacing (again on desktop sizes above 1365px).

image

5. Both of the above should be 160px (when measured) on large desktop screens larger than 1365px. On smaller desktop screens (1025px to 1365px), it should be 140px, again on both.

6. The spacing above the dates on desktop when the picture is to the side of the copy is now too small. It looks good when the picture is above the copy on smaller screens. But on larger screens when the picture is to the side of the copy, the space above the date should be 45px (currently displaying as 20px).

image

8. Lastly, from 768px to 1024px the Resources copy should be above the photo just like the other content blocks (I just noticed this.)

image

If you'd like to connect to walk through any of this, let me know. This week is very flexible on our end.

**Comment by SaVanceX** [comment]
@YaGirlSherriJ Looks like the changes I made shifted some of the measurements possibly?

**Comment by SaVanceX** [comment]
@YaGirlSherriJ  For number 1.  Are you saying the height should be 6px smaller or both width and height should be 6px smaller?

**Comment by SaVanceX** [comment]
@YaGirlSherriJ Also it probably wouldn't hurt if we paired up this week. Just let me know what time works best for you

**Comment by SaVanceX** [comment]
@YaGirlSherriJ  made updates for Number 1. https://deploy-preview-351--phot-production.netlify.app/ 
Also just curious what tool are you using for these measurements? From what I see from the screenshots it looks very useful

**Comment by YaGirlSherriJ** [comment]
> @YaGirlSherriJ For number 1. Are you saying the height should be 6px smaller or both width and height should be 6px smaller?

@SaVanceX Just height, sorry.

**Comment by YaGirlSherriJ** [comment]
> @YaGirlSherriJ made updates for Number 1. https://deploy-preview-351--phot-production.netlify.app/ Also just curious what tool are you using for these measurements? From what I see from the screenshots it looks very useful

@SaVanceX looks good, thank you!

I'm using the web inspector on Firefox (Windows).

**Comment by YaGirlSherriJ** [comment]
> @YaGirlSherriJ Also it probably wouldn't hurt if we paired up this week. Just let me know what time works best for you

@SaVanceX no problem. How does tomorrow at 1:30pm ET work for you?

**Comment by SaVanceX** [comment]
@YaGirlSherriJ Ah gotcha! And 1:30pm ET tomorrow works for me.

**Comment by YaGirlSherriJ** [comment]
@SaVanceX sounds good, I'll send a calendar invite shortly 😁

**Comment by YaGirlSherriJ** [comment]
@SaVanceX you beat me to it lol! Will you be adding a meeting link, or would you like me to create one?

**Comment by SaVanceX** [comment]
@YaGirlSherriJ  just added one

**Comment by YaGirlSherriJ** [comment]
Thank you!

**Comment by SaVanceX** [comment]
@YaGirlSherriJ made some more updates https://deploy-preview-351--phot-production.netlify.app/

**Comment by SaVanceX** [comment]
@YaGirlSherriJ  updates! https://deploy-preview-351--phot-production.netlify.app/

**Comment by YaGirlSherriJ** [comment]
@SaVanceX Sorry I missed this earlier! 

On screen sizes below 1365 the first row is still 10px too big. Other than than, everything looks great, thank you!!

**Comment by SaVanceX** [comment]
@YaGirlSherriJ update should be good to go https://deploy-preview-351--phot-production.netlify.app/

**Comment by YaGirlSherriJ** [comment]
@SaVanceX Beautiful! Thank you so much for all your work on this 🙏 - please let me know when it's live.

**Pull request merged**
